### ISSUE TITLE
Questions regarding the choice of the normal distribution

### ISSUE THREAD

**Issue by Meng-Wei** [cmu-ci-lab/volumetric_opaque_solids#1]
Hi, thanks for your excellent work.

I have a question related to the choice of the normal distribution.
If I choose the Gaussian distribution as the density function, should this setting also determine the normal distribution, like the gradient of the density function? Why can I freely choose the normal distribution?

Thank you in advance!

**Comment by baileymiller** [comment]
Apologies for the very delayed response and thank you for the question! 

No, the distribution of normals (delta, mixture, sggx, etc.) is chosen separately from the distribution of the stochastic implicit surface (Logistic, Laplace, Gaussian, etc.). The only relation between the two is that the distribution of normals is chosen to be centered on the gradient of the mean implicit surface (eq 20 in [our paper](https://www.bailey-miller.com/data/papers/miller24oav.pdf)). 

This type of model is known as a "microgeometry" model in graphics (refer to microfacets in surface rendering [PBRT](https://pbr-book.org/4ed/Reflection_Models/Roughness_Using_Microfacet_Theory), or microflakes in volume rendering [microflakes](https://www.cs.cornell.edu/~kb/publications/SIG10Aniso.pdf), [sggx](https://research.nvidia.com/sites/default/files/pubs/2015-08_The-SGGX-microflake/sggx.pdf)). Whereas microgeometry  typically uses a distribution of normals to model the aggregate effects of fine-scale geometry,  we use a distribution of normals to capture the ambiguity in normals at points inside (vacancy is << 0.5) or outside (vacancy is >> 0.5) of a stochastic opaque solid.

We noticed that modeling this normal ambiguity can have a large impact on performance and even prior work like NeuS uses a trick during training which can be understood as adding a sort of global ambiguity to normals (https://github.com/Totoro97/NeuS/blob/main/models/renderer.py#L232-L235).

**Comment by Meng-Wei** [comment]
Thanks for your reply!

**Comment by baileymiller** [comment]
No problem!
